#!/bin/bash

echo "========================================="
echo "Whisperz - Push to GitHub Helper"
echo "========================================="
echo ""
echo "This script will help you push the code to your GitHub repository."
echo ""
echo "Option 1: Use GitHub CLI (if you have it installed)"
echo "----------------------------------------"
echo "Run: gh auth login"
echo "Then: git push -u origin main"
echo ""
echo "Option 2: Use HTTPS with Personal Access Token"
echo "----------------------------------------"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Generate new token (classic) with 'repo' scope"
echo "3. Run the following command:"
echo ""
echo "git remote set-url origin https://YOUR_TOKEN@github.com/danxdz/Whisperz.git"
echo "git push -u origin main"
echo ""
echo "Option 3: Use SSH"
echo "----------------------------------------"
echo "1. Set up SSH keys: https://docs.github.com/en/authentication/connecting-to-github-with-ssh"
echo "2. Run:"
echo "git remote set-url origin git@github.com:danxdz/Whisperz.git"
echo "git push -u origin main"
echo ""
echo "Option 4: Download and push from your local machine"
echo "----------------------------------------"
echo "1. Download the project files from this workspace"
echo "2. On your local machine:"
echo "   git clone https://github.com/danxdz/Whisperz.git"
echo "   cd Whisperz"
echo "   # Copy all files from workspace to this directory"
echo "   git add ."
echo "   git commit -m 'Complete Whisperz implementation'"
echo "   git push origin main"
echo ""
echo "Current commits ready to push:"
echo "----------------------------------------"
git log --oneline -3
echo ""
echo "========================================="